---

- name: FUN development stack
  hosts: all
  remote_user: vagrant
  sudo: yes

  vars:
    edxapp_root: "/edx/app"
    edxapp_home: "{{ edxapp_root }}/edxapp"
    virtualenv: "{{ edxapp_home }}/venvs/edxapp"
    edx_ansible_venv: "{{ edxapp_root }}/edx_ansible/venvs/edx_ansible"
    python: "{{ virtualenv }}/bin/python"
    mount_base: "{{ lookup('env', 'VAGRANT_MOUNT_BASE') }}"
    edx_platform_github: "https://github.com/openfun/edx-platform"
    edx_platform_remote_name: "fun"
    fun_github: "https://github.com/openfun/fun-apps"

  tasks:
    - name: Update apt cache
      apt: update_cache=yes cache_valid_time=3600
    - name: Install mysql 5.6
      apt: name=mysql-server state=present
    - name: Install external version of meliae (not installable via pypi)
      apt: name=python-meliae state=present

    - debug: var=mount_base

    - name: Checkout fun-apps code
      git: repo={{ fun_github }} dest={{ edxapp_home }}/fun-apps/ version={{ fun_release }}
      sudo_user: edxapp

    - name: Checks whether we have a remote named fun already
      command: /bin/grep -q "{{ edx_platform_remote_name }}" {{ edxapp_home }}/edx-platform/.git/config
      register: checkgitremote
      sudo_user: edxapp
      always_run: True
      ignore_errors: True
      changed_when: False

    - debug: var=checkgitremote

    - name: Add fun origin as remote
      command: /usr/bin/git remote add {{ edx_platform_remote_name }} {{ edx_platform_github }} chdir={{ edxapp_home }}/edx-platform
      when: checkgitremote == 1
      sudo_user: edxapp

    - name: Checkout edx-platform code at the right version {{ openedx_fun_release }}
      git: repo={{ edx_platform_github }} dest={{ edxapp_home }}/edx-platform/ version={{ openedx_fun_release }}
           remote={{ edx_platform_remote_name }}
      when: checkgitremote == 1
      sudo_user: edxapp

    - name: Fix venv permissions
      file:
        path={{ edx_ansible_venv }}
        state=directory
        recurse=yes owner=edx-ansible group=edx-ansible
    - name: Create test report folder
      file: state=directory path={{ edxapp_home }}/edx-platform/reports/
      sudo_user: edxapp
    - name: Create test report lms folder
      file: state=directory path={{ edxapp_home }}/edx-platform/reports/lms
      sudo_user: edxapp
    - name: Create test report cms folder
      file: state=directory path={{ edxapp_home }}/edx-platform/reports/cms
      sudo_user: edxapp
    - name: Create .testids folder
      file: state=directory path={{ edxapp_home }}/edx-platform/.testids/
      sudo_user: edxapp
    - name: Create .testids lms folder
      file: state=directory path={{ edxapp_home }}/edx-platform/.testids/lms
      sudo_user: edxapp
    - name: Create .testids cms folder
      file: state=directory path={{ edxapp_home }}/edx-platform/.testids/cms
      sudo_user: edxapp
    - name: Create attestations folder
      file: state=directory path=/edx/var/edxapp/attestations/
      sudo_user: edxapp
    - name: Create ora2 folder
      file: state=directory path=/edx/var/edxapp/shared/openassessment_submissions
      sudo_user: edxapp

    - name: Symlink lms.envs and cms.envs
      file: src={{ edxapp_home }}/fun-apps/fun/envs/lms/dev.py dest={{ edxapp_home }}/edx-platform/lms/envs/fundev.py state=link
      sudo_user: edxapp
      file: src={{ edxapp_home }}/fun-apps/fun/envs/cms/dev.py dest={{ edxapp_home }}/edx-platform/cms/envs/fundev.py state=link
      sudo_user: edxapp

    - name: Install fun-apps base requirements
      pip: virtualenv={{ virtualenv }} requirements="{{ edxapp_home }}/fun-apps/requirements/base.txt"
      sudo_user: edxapp
    - name: Install fun-apps dev requirements
      pip: virtualenv={{ virtualenv }} requirements="{{ edxapp_home }}/fun-apps/requirements/dev.txt"
      sudo_user: edxapp

    - name: Syncdb for lms
      command: "{{ edxapp_home }}/edx-platform/manage.py lms --settings=fundev syncdb"
      args:
          chdir: "{{ edxapp_home }}/edx-platform"
      sudo_user: edxapp

    - name: Syncdb for cms
      shell: "{{ edxapp_home }}/edx-platform/manage.py cms --settings=fundev syncdb"
      args:
          chdir: "{{ edxapp_home }}/edx-platform"
      sudo_user: edxapp

    - name: Migrate lms
      shell: "{{ edxapp_home }}/edx-platform/manage.py lms --settings=fundev migrate"
      args:
          chdir: "{{ edxapp_home }}/edx-platform"
      sudo_user: edxapp
    - name: Migrate cms
      shell: "{{ edxapp_home }}/edx-platform/manage.py cms --settings=fundev migrate"
      args:
          chdir: "{{ edxapp_home }}/edx-platform"
      sudo_user: edxapp