---

- name: Upgrade FUN development stack
  hosts: all
  remote_user: vagrant
  sudo: yes
  sudo_user: edxapp

  vars:
    edxapp_root: "/edx/app"
    edxapp_home: "{{ edxapp_root }}/edxapp"
    virtualenv: "{{ edxapp_home }}/venvs/edxapp"

  tasks:

    - name: Checkout fun-apps code
      git: repo=https://github.com/openfun/fun-apps dest={{ edxapp_home }}/fun-apps/ version={{ fun_release }}
    - name: Checkout themes/fun code
      git: repo=https://github.com/openfun/edx-theme dest={{ edxapp_home }}/themes/fun version={{ fun_release }}
    - name: Checkout edx-platform code
      git: repo=https://github.com/openfun/edx-platform dest={{ edxapp_home }}/edx-platform/ version={{ openedx_fun_release }}

    - name: Update requirements
      shell: "{{ virtualenv }}/bin/fun lms.dev requirements"
    - name: Generate lms assets
      shell: "{{ virtualenv }}/bin/fun lms.dev assets"
    - name: Generate cms assets
      shell: "{{ virtualenv }}/bin/fun cms.dev assets"

    - name: Migrate lms
      shell: "{{ virtualenv }}/bin/fun lms.dev migrate"
      args:
          chdir: "{{ edxapp_home }}/edx-platform"
    - name: Migrate cms
      shell: "{{ virtualenv }}/bin/fun cms.dev migrate"
      args:
          chdir: "{{ edxapp_home }}/edx-platform"
